services:
  life-kline:
    build: .
    container_name: life-kline
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./server/data:/app/server/data
